#pragma once

#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 120
#define TAPPING_TERM 180

#define COMBO_TERM 40

#define MASTER_RIGHT

#define MOU_BRR_INTERVAL 40

#ifdef MOUSEKEY_ENABLE
#    define MOUSEKEY_DELAY 10
#    define MOUSEKEY_INTERVAL 20
#    define MOUSEKEY_MOVE_DELTA 8
#    define MOUSEKEY_MAX_SPEED 10
#    define MOUSEKEY_TIME_TO_MAX 30
#    define MOUSEKEY_WHEEL_DELAY 10
#    define MOUSEKEY_WHEEL_INTERVAL 80
#    define MOUSEKEY_WHEEL_DELTA 1
#    define MOUSEKEY_WHEEL_MAX_SPEED 8
#    define MOUSEKEY_WHEEL_TIME_TO_MAX 40
#endif
